#!/usr/bin/bash
cd $SCRATCH/python_project
module load GCCcore/8.3.0
module load Python/3.7.4
source venv/bin/activate

# Use the first argument as batch_dir
batch_dir=$1
echo Preping batch on $batch_dir

start_proj='$SCRATCH/dissolCases'
dissolCases_dir=$SCRATCH/dissolCases/$batch_dir

# Loop through all subdirectories and close fracture
cd $dissolCases_dir
python -c "from OFPy import OFPy_prep_batch; OFPy_prep_batch.prep_batch('$dissolCases_dir' , '$start_proj')"
deactivate

ln -s ../OFPy_batch/CondBatch.sbatch .
ln -s ../OFPy_batch/CondBatchSlow.sbatch .

echo All cases are prepared at $dissolCases_dir
